os:
  - linux
language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

notifications:
  email:
    - barcher4620@gmail.com
install:
  - npm install -g
  - mv node_modules npm
  - npm/.bin/npm --version
  - npm install tap
  - npm/.bin/npm install
  - npm/.bin/npm update
  - ls -la
script: node_modules/.bin/tap --gc argumints-test.js