os:
  - linux
  - osx
language: JAVASCRIPT

env:
  matrix:
  - TRAVIS_NODE_VERSION="0.8"
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="iojs-3"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="5"
notifications:
  email:
    - barcher4620@gmail.com
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then npm install npm@2 && node_modules/.bin/npm install npm; else npm install npm; fi
  - mv node_modules npm
  - npm/.bin/npm --version
  - npm/.bin/npm install
  - node_modules/.bin/node-gyp rebuild --directory test
script: node_modules/.bin/tap --gc *-test.js