os:
  - linux
language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

notifications:
  email:
    - barcher4620@gmail.com
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then npm install npm@2 && node_modules/.bin/npm install npm; else npm install npm; fi
  - mv node_modules npm
  - npm/.bin/npm --version
  - npm/.bin/npm install
  - npm/.bin/npm update
#  - node_modules/.bin/node-gyp rebuild
script: node_modules/.bin/tap --gc argumints-test.js